// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace PlaywrightTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Product Page")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class ProductPageFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Product Page", "    Testing the Product feature of application", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Product.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 4
 #line hidden
#line 5
  await testRunner.GivenAsync("I navigate to the Product page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Product.feature.ndjson", 15);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify Product Page Is Displayed Correctly")]
        [global::NUnit.Framework.CategoryAttribute("productPage")]
        public async global::System.Threading.Tasks.Task VerifyProductPageIsDisplayedCorrectly()
        {
            string[] tagsOfScenario = new string[] {
                    "productPage"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify Product Page Is Displayed Correctly", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 8
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
 await this.FeatureBackgroundAsync();
#line hidden
#line 9
  await testRunner.ThenAsync("The product item should be displayed correctly with complete details", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Search Product By Keyword")]
        [global::NUnit.Framework.CategoryAttribute("searchProduct")]
        [global::NUnit.Framework.TestCaseAttribute("Automatic", "2", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("Air", "9", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("blender", "2", "3", null)]
        public async global::System.Threading.Tasks.Task SearchProductByKeyword(string keyword, string numberOfProductsExpected, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "searchProduct"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("keyword", keyword);
            argumentsOfScenario.Add("numberOfProductsExpected", numberOfProductsExpected);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Search Product By Keyword", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
 await this.FeatureBackgroundAsync();
#line hidden
#line 13
  await testRunner.WhenAsync(string.Format("I enter the product name \"{0}\" in the search field", keyword), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 14
  await testRunner.ThenAsync(string.Format("the system should display {0} suggestion items for keyword \"{1}\"", numberOfProductsExpected, keyword), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 15
  await testRunner.ThenAsync(string.Format("the product suggestion item should display with correct details keyword \"{0}\"", keyword), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 16
  await testRunner.WhenAsync(string.Format("I click on the view all results button based on keyword \"{0}\"", keyword), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 17
  await testRunner.ThenAsync(string.Format("the product search result should be verified based on keyword \"{0}\" and count {1}" +
                            "", keyword, numberOfProductsExpected), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Search Non-Existing Product Shows No Products Found Message")]
        [global::NUnit.Framework.CategoryAttribute("searchProduct")]
        [global::NUnit.Framework.TestCaseAttribute("abc", "0", "No products found", "4", null)]
        public async global::System.Threading.Tasks.Task SearchNon_ExistingProductShowsNoProductsFoundMessage(string keyword, string numberOfProductsExpected, string suggestionMessage, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "searchProduct"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("keyword", keyword);
            argumentsOfScenario.Add("numberOfProductsExpected", numberOfProductsExpected);
            argumentsOfScenario.Add("suggestionMessage", suggestionMessage);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Search Non-Existing Product Shows No Products Found Message", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
 await this.FeatureBackgroundAsync();
#line hidden
#line 26
  await testRunner.WhenAsync(string.Format("I enter the product name \"{0}\" in the search field", keyword), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 27
  await testRunner.ThenAsync(string.Format("the system should display {0} suggestion items for keyword \"{1}\"", numberOfProductsExpected, keyword), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 28
  await testRunner.AndAsync(string.Format("the no products found suggestion message should be visible with text \"{0}\"", suggestionMessage), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
  await testRunner.WhenAsync("I press enter on the search field", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 30
  await testRunner.ThenAsync(string.Format("the product search result URL should be verified based on keyword \"{0}\"", keyword), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 31
  await testRunner.AndAsync(string.Format("the search results heading for \"{0}\" should be visible", keyword), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
  await testRunner.AndAsync(string.Format("the product search result count should show {0} products", numberOfProductsExpected), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
  await testRunner.AndAsync("the no products found label should be visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Sort Product")]
        [global::NUnit.Framework.CategoryAttribute("sortProduct")]
        [global::NUnit.Framework.TestCaseAttribute("Price (high-low)", "8", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("Name (A-Z)", "8", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("Name (Z-A)", "8", "7", null)]
        public async global::System.Threading.Tasks.Task SortProduct(string sortOption, string numberOfSortOptions, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "sortProduct"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("sortOption", sortOption);
            argumentsOfScenario.Add("numberOfSortOptions", numberOfSortOptions);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Sort Product", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 39
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
 await this.FeatureBackgroundAsync();
#line hidden
#line 40
  await testRunner.GivenAsync("I navigate to the Product page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 41
  await testRunner.WhenAsync(string.Format("I open the sort dropdown and select option \"{0}\"", sortOption), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
  await testRunner.ThenAsync(string.Format("the total number of sort options should be {0}", numberOfSortOptions), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 43
  await testRunner.AndAsync(string.Format("the product list should be sorted correctly based on \"{0}\"", sortOption), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Filter Products By Color")]
        [global::NUnit.Framework.CategoryAttribute("filterProduct")]
        [global::NUnit.Framework.TestCaseAttribute("Rose Gold, Silver, Mint", "3", "19", "8", null)]
        [global::NUnit.Framework.TestCaseAttribute("Blue and White, Black and Red, Graphite", "3", "19", "9", null)]
        public async global::System.Threading.Tasks.Task FilterProductsByColor(string colors, string expectedSelectedColorCount, string expectedNumberOption, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "filterProduct"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("colors", colors);
            argumentsOfScenario.Add("expectedSelectedColorCount", expectedSelectedColorCount);
            argumentsOfScenario.Add("expectedNumberOption", expectedNumberOption);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Filter Products By Color", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 52
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
 await this.FeatureBackgroundAsync();
#line hidden
#line 53
  await testRunner.GivenAsync("I navigate to the Product page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 54
  await testRunner.WhenAsync("I click the filter color button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
  await testRunner.ThenAsync(string.Format("the total number of available color options should be {0}", expectedNumberOption), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 56
  await testRunner.WhenAsync(string.Format("I select the color options \"{0}\"", colors), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
  await testRunner.AndAsync("I close the color filter menu", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
  await testRunner.ThenAsync(string.Format("the selected color count on the filter button should be {0}", expectedSelectedColorCount), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 59
  await testRunner.AndAsync(string.Format("the selected color tags should be displayed correctly as \"{0}\"", colors), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
  await testRunner.AndAsync("at least one product should be displayed after color filtering", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
  await testRunner.AndAsync(string.Format("each checked product detail should contain at least one of the selected colors \"{" +
                            "0}\"", colors), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Filter Product By Price")]
        [global::NUnit.Framework.CategoryAttribute("filterProduct")]
        [global::NUnit.Framework.TestCaseAttribute("$200+", "4", "1", "10", null)]
        public async global::System.Threading.Tasks.Task FilterProductByPrice(string priceRange, string priceOptionCount, string expectedPriceCount, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "filterProduct"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("priceRange", priceRange);
            argumentsOfScenario.Add("priceOptionCount", priceOptionCount);
            argumentsOfScenario.Add("expectedPriceCount", expectedPriceCount);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Filter Product By Price", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 69
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
 await this.FeatureBackgroundAsync();
#line hidden
#line 70
  await testRunner.WhenAsync("I open the price filter menu", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 71
  await testRunner.ThenAsync(string.Format("the system should display {0} price options", priceOptionCount), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 72
  await testRunner.WhenAsync(string.Format("I select the price range option \"{0}\"", priceRange), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
  await testRunner.WhenAsync("I close the price filter menu", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 74
  await testRunner.ThenAsync(string.Format("the selected price count should be {0}", expectedPriceCount), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 75
  await testRunner.AndAsync(string.Format("the selected price tag should be displayed correctly as \"Price: {0}\"", priceRange), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
  await testRunner.AndAsync("at least one product should be displayed after price filtering", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
  await testRunner.AndAsync(string.Format("each checked product detail should fall within the price range greater than \"{0}\"" +
                            "", priceRange), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Filter Product By Availability")]
        [global::NUnit.Framework.CategoryAttribute("filterProduct")]
        [global::NUnit.Framework.TestCaseAttribute("3", "In Stock", "true", "36", "11", null)]
        [global::NUnit.Framework.TestCaseAttribute("3", "Out of Stock", "false", "0", "12", null)]
        public async global::System.Threading.Tasks.Task FilterProductByAvailability(string expectedOptionCount, string selectedAvailability, string hasProductsExpected, string numberOfProductsExpected, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "filterProduct"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("expectedOptionCount", expectedOptionCount);
            argumentsOfScenario.Add("selectedAvailability", selectedAvailability);
            argumentsOfScenario.Add("hasProductsExpected", hasProductsExpected);
            argumentsOfScenario.Add("numberOfProductsExpected", numberOfProductsExpected);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Filter Product By Availability", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 84
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
 await this.FeatureBackgroundAsync();
#line hidden
#line 85
   await testRunner.WhenAsync("I open the availability filter menu", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 86
   await testRunner.ThenAsync(string.Format("the system should display \"{0}\" availability options", expectedOptionCount), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 87
   await testRunner.WhenAsync(string.Format("I select the availability option \"{0}\"", selectedAvailability), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 88
   await testRunner.WhenAsync("I close the availability filter menu", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 89
   await testRunner.ThenAsync(string.Format("the product filtering result by availability should be verified based on expectat" +
                            "ion \"{0}\" and count \"{1}\"", hasProductsExpected, numberOfProductsExpected), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 90
   await testRunner.AndAsync(string.Format("the selected availability tags should be displayed correctly as \"{0}\"", selectedAvailability), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
