name: Playwright Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: 'Which browser to test'
        required: true
        options:
          - firefox
          - chromium
          - webkit

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.slnx') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build

    - name: Install Playwright Browsers & Dependencies
      run: |
        dotnet tool install --global Microsoft.Playwright.CLI
        playwright install

    - name: Run NUnit Tests
      run: |
        dotnet test

    - name: Get Allure Report history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true

    - name: Build Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_report: allure-report
        keep_reports: 20


    - name: Upload Allure Report Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report
        path: allure-report
        retention-days: 30